### PR TITLE
48 blog show page

### LINKED ISSUE #48: Add show view for an individual blog post with URL
Right now there is no way to share with someone a specific post in the blog. I should have the ability to click on a blog post title in the `/blog` page and go to a view that just contains that blog post with a unique link I can send to someone.

### PR DESCRIPTION
**Pull request by mikestone14**
closes #48 

This PR renders an individual blog post. The url for a blog post is `/blog/blog%20post%20title`.

### CODE REVIEW

**Comment by terracatta** [comment]
> The url for a blog post is /blog/blog%20post%20title

Anything we can do to "slugify" the title?

**Comment by mikestone14** [comment]
@terracatta do you have any thoughts on how you'd like to slugify it?

**Comment by terracatta** [comment]
```javascript
function slugify(text)
{
  return text.toString().toLowerCase()
    .replace(/\s+/g, '-')           // Replace spaces with -
    .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
    .replace(/\-\-+/g, '-')         // Replace multiple - with single -
    .replace(/^-+/, '')             // Trim - from start of text
    .replace(/-+$/, '');            // Trim - from end of text
}
```

**Comment by mikestone14** [comment]
Thanks @terracatta - ready for re-review.

**Pull request merged**
